name: to main server
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  repository_dispatch:
    types: [triggered-event]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Confirm start'     
        required: false
        default: 'yes'
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: lamasatech
          password: ${{ secrets.DOCKER_KEY }}
      - name: docker build
        run: |
          docker build -t lamasatech/janus-gateway:0.12.3 -f ./deploy/images/janus-gateway/Dockerfile .
          docker push lamasatech/janus-gateway:0.12.3  
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}

  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to server
        run: |
          ssh-keygen -R remote.visipoint.dev
          ssh-keyscan -t rsa remote.visipoint.dev >> /home/runner/.ssh/known_hosts
          ssh  -o StrictHostKeyChecking=no root@remote.visipoint.dev "cd remote-control && docker-compose pull janus && docker-compose up -d"
