name: front-end deploy
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
    paths:
      - 'web-admin/**'
  repository_dispatch:
    types: [triggered-event]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Confirm start'     
        required: false
        default: 'yes'
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # copy files to server
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ssh
        uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Deploy to server
        run: |
          rsync -crvl  -e "ssh -o StrictHostKeyChecking=no" \
          --exclude=/storage \
          /web-admin root@remote.visipoint.dev:/root/remote-control/web-admin
          ssh  -o StrictHostKeyChecking=no root@remote.visipoint.dev "ansible-playbook /root/remote-control/deploy/pre_webadmin.yaml"
